fishing:
  x: 547
  y: 222
  width: 602
  height: 635
  timeouts:
    loop:
      min: 0.01
      max: 0.01
    notice:
      min: 1.5
      max: 2.0
    reeling:
      min: 0.7
      max: 1.7
    pause:
      min: 0.5
      max: 1.5
    cast:
      min: 0.5
      max: 1.0
repairing:
  x: 860
  y: 665
  length: 25
  every: 400
  enable: 1
  timeouts:
    arm_disarm:
      min: 1
      max: 1.5
    inventory:
      min: 1
      max: 1.5
    repair:
      min: 1
      max: 1.5
    confirm:
      min: 1
      max: 1.5
    move_around:
      min: 0.5
      max: 1.0
bait:
  bait_x: 1174
  bait_y: 455
  equip_button_x: 1406
  equip_button_y: 815
  length: 25
  enable: 1
  timeouts:
    select:
      min: 0.1
      max: 1
    confirm:
      min: 0.1
      max: 1
colors:
  green:
    r: 4
    g: 227
    b: 162
  brown:
    r: 230
    g: 110
    b: 22
  red:
    r: 109
    g: 18
    b: 21
resolution:
  x: 5120
  y: 2160
log_lvl: INFO
